### ISSUE TITLE
Getting Critical Errors

### ISSUE THREAD

**Issue by jo-phish** [AxesOfEvil/NGU-save-parser#1]
Running on Win 10 , Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]

cmdline: optimize.py --inf NGUSave-pts.txt --stat power --acc 5

output:

CRITICAL:root:No special divisor found for Cooking (Item: 78 - Chef's Hat @ 2,0/1 2,0/1: Cooking
CRITICAL:root:No special divisor found for EnergyPower (Item: 78 - Chef's Hat @ 2,0/2 2,0/2: EnergyPower
CRITICAL:root:No special divisor found for Cooking (Item: 79 - Chef's Apron @ 2,1/1 2,1/1: Cooking
CRITICAL:root:No special divisor found for EnergyPower (Item: 79 - Chef's Apron @ 2,1/2 2,1/2: EnergyPower
CRITICAL:root:No special divisor found for Cooking (Item: 80 - Regular Pants @ 2,2/1 2,2/1: Cooking
CRITICAL:root:No special divisor found for EnergyPower (Item: 80 - Regular Pants @ 2,2/2 2,2/2: EnergyPower
CRITICAL:root:No special divisor found for Cooking (Item: 81 - Non Slip Shoes @ 2,3/1 2,3/1: Cooking
CRITICAL:root:No special divisor found for EnergyPower (Item: 81 - Non Slip Shoes @ 2,3/2 2,3/2: EnergyPower
CRITICAL:root:No special divisor found for Cooking (Item: 82 - Bloody Cleaver @ 2,4/1 2,4/1: Cooking
CRITICAL:root:No special divisor found for EnergyPower (Item: 82 - Bloody Cleaver @ 2,4/2 2,4/2: EnergyPower
CRITICAL:root:No special divisor found for EnergyPerBar (Item: 82 - Bloody Cleaver @ 2,4/3 2,4/3: EnergyPerBar
CRITICAL:root:No special divisor found for EnergyPerBar (Item: 68 - Magitech Helmet @ 2,6/1 2,6/1: EnergyPerBar
CRITICAL:root:No special divisor found for MagicPerBar (Item: 68 - Magitech Helmet @ 2,6/2 2,6/2: MagicPerBar
CRITICAL:root:No special divisor found for EnergyPerBar (Item: 69 - Magitech Chestplate @ 2,7/1 2,7/1: EnergyPerBar
CRITICAL:root:No special divisor found for MagicSpeed (Item: 69 - Magitech Chestplate @ 2,7/2 2,7/2: MagicSpeed
CRITICAL:root:No special divisor found for MagicPerBar (Item: 70 - Magitech Leggings @ 2,8/1 2,8/1: MagicPerBar
CRITICAL:root:No special divisor found for MagicPower (Item: 70 - Magitech Leggings @ 2,8/2 2,8/2: MagicPower
CRITICAL:root:No special divisor found for EnergyPower (Item: 71 - Magitech Boots @ 2,9/1 2,9/1: EnergyPower
CRITICAL:root:No special divisor found for MagicPower (Item: 71 - Magitech Boots @ 2,9/2 2,9/2: MagicPower
CRITICAL:root:No special divisor found for EnergyPower (Item: 74 - Magitech Amulet @ 2,11/1 2,11/1: EnergyPower
CRITICAL:root:No special divisor found for MagicPower (Item: 73 - Magitech Ring @ 3,1/1 3,1/1: MagicPower
CRITICAL:root:No special divisor found for MagicSpeed (Item: 59 - Havarti Ring @ 3,2/1 3,2/1: MagicSpeed
CRITICAL:root:No special divisor found for MagicPower (Item: 59 - Havarti Ring @ 3,2/2 3,2/2: MagicPower
CRITICAL:root:No special divisor found for EnergyPower (Item: 60 - Cheddar Amulet @ 3,4/1 3,4/1: EnergyPower
CRITICAL:root:No special divisor found for EnergySpeed (Item: 60 - Cheddar Amulet @ 3,4/2 3,4/2: EnergySpeed
CRITICAL:root:No special divisor found for MagicSpeed (Item: 435 - Magicite Crystal @ 3,8/2 3,8/2: MagicSpeed
CRITICAL:root:No special divisor found for MagicPower (Item: 434 - A Dragon's Left Ball @ 3,9/2 3,9/2: MagicPower
CRITICAL:root:No special divisor found for MagicSpeed (Item: 433 - Cheese Grater @ 3,10/2 3,10/2: MagicSpeed
CRITICAL:root:No special divisor found for EnergySpeed (Item: 433 - Cheese Grater @ 3,10/3 3,10/3: EnergySpeed

[NGUSave-pts.txt](https://github.com/AxesOfEvil/NGU-save-parser/files/6804289/NGUSave-pts.txt)
 
Attached save file but happening on others

Hope this was a good place to put this
-jophish

**Comment by AxesOfEvil** [comment]
This is because I'm too far into the game, and I don't have items with these attributes anymore.
I have updated the code with multipliers for these.  Let me know if you still have any issues

**Comment by jo-phish** [comment]
Thanks. I kind of figured that was what was going on (I just started - god help me).  Hadn't found it in the code yet. are the multipliers for the item that level partial depending on  boss level?

**Comment by AxesOfEvil** [comment]
As you go up in zones, the items become harder to boost to their final value.  so for instance early in the game you may get an item with 100% boost to energy_power that takes 100 special-boosts to max.  At higher levels, you'll find an item that needs 1000 special boosts to get to 100%.  An item like this has a divisor of 10.  The biggest divisor I've seen so far is 1e6 which takes a million boosts to give a 1% improvement
