### ISSUE TITLE
Pymoo breaking changes & "Unknown element type 14 for unknown"

### ISSUE THREAD

**Issue by tex0l** [AxesOfEvil/NGU-save-parser#2]
Hi,
I'm trying to use this project for optimizing my gear (I'm in SAD around the construction zone) with build 1.260.

First, apparently I had to change some imports because `pymoo` had some breaking changes, and it doesn't work on my end (https://pymoo.org/versions.html) with v0.5.0, you should consider adding a requirements.txt to set the `pymoo` version :).

Then, when I tried to start an optimize command, it failed with the following error:
```
Unknown element type 14 for unknown
CRITICAL:root:Failed to read save_file: 322
```

I have no idea how to debug this. Do you know of some documentation on this file format I could use to understand how this f**ery works?

(btw thanks for this tool, I honestly don't know why I'm spending that much time on this 🤷‍♂️)

**Comment by PhracturedBlue** [comment]
this likely means that the save-game file format has changed again.  I' not currently playing NGU, but I'll try to take a look when I get a chance.

In the mean time, try adding this at deserialize_dot_net.py line 339:
```
            elif elem == 14:  # array of 32bit null
                self.pos += 1
                count = self.read_u32()
                return None, [None for _ in range(0, count)]
```

This is the best spec I've found for the BinaryFormatter serialization, and it is what my code is based on:
https://web.archive.org/web/20120625224455/http://primates.ximian.com/~lluis/dist/binary_serialization_format.htm

**Comment by tex0l** [comment]
Thank you for the reference documentation and the tip 🙏 , I couldn't find any reference 😭. With that, I can try to understand :)

btw I have another error that comes up, even though I haven't changed anything yet (except more logs) 🤔 :

```
ERROR:root:Unknown element type 6 for cooking
```

**Comment by tex0l** [comment]
By the way, I found this reference document as well: https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-NRBF/%5bMS-NRBF%5d.pdf

**Comment by PhracturedBlue** [comment]
That one is interesting.
type 6 is a string, but for some reason the tag-type is not '1'
You can try this, but I'm not sure this will actually work.
deserialize_dot_net.py line 324:
```
        elif elem == 6:  # string
            LOG.warning("Element 6 type-tag: %s", type_tag)
            self.pos += 1
            _id = self.read_u32()
            return _id, self.read_str()
```
This may be an array-type object.  if you provide the  output of that warning message, it might help identify what is going on.  I may need a copy of your save file if this doesn't work, since I doubt I have a save-game that will contain this item.

**Comment by AxesOfEvil** [comment]
I have updated the README to specify the pymoo version.  I'll add a requirements.txt next time I update the code.

**Comment by tex0l** [comment]
I already did this, and it successfully finishes parsing the save file and made a JSON out of it.

The log you asked for is: `WARNING:root:Element 6 type-tag: 4`.

However, once this parsing step works, I have an issue with the `parse_items` function which fails at this line:
```
    inventory = sav['inventory']['value']
```
with
```
KeyError: 'value'
```

The content of the `sav['inventory']` is: `{'type': 4, 'code': ('Inventory', 2)}` which confuses me, and makes me think the whole save file parsing fails.

BTW, I found this repo which implements a BinaryFormat parser: https://github.com/williballenthin/python-dotnet-binaryformat, however it fails with NotImplemented (I think this one: https://github.com/williballenthin/python-dotnet-binaryformat/blob/34eb3956ce10a1165dc6334257de2c4ac3f22d86/dnbinaryformat/__init__.py#L93) 


ERRATUM: I tested more precisely where the NotImplemented comes from, and it's just the catchall NotImplemented at the end...

**Comment by PhracturedBlue** [comment]
Your results do far indicate that the parser is deserializing, but it is quite possible that there has been a structural change to the data (though I'd find that pretty odd, since there hasn't been a huge amount of new development).

You might try using the --json switch.  I think it will just dump the raw structure of the savegame, which may help you figure out what changed.

Otherwise you'll need to wait for me to try it out.

**Comment by tex0l** [comment]
The JSON contains surprisingly very little data:
```
{
  "NGU": {
    "code": [
      "NUMBERSSGOUP",
      2
    ],
    "type": 4
  },
  "__cname__": "PlayerData",
  "achievements": {
    "code": [
      "AchievementList",
      2
    ],
    "type": 4
  },
  "advancedTraining": {
    "code": [
      "AdvancedTraining",
      2
    ],
    "type": 4
  },
  "adventure": {
    "code": [
      "Adventure",
      2
    ],
    "type": 4
  },
  "arbitrary": {
    "code": [
      "Arbitrary",
      2
    ],
    "type": 4
  },
  "attack": {
    "code": 6,
    "type": 0
  },
  "attackBoost": {
    "code": 11,
    "type": 0
  },
  "attackMulti": {
    "code": 6,
    "type": 0
  },
  "augments": {
    "code": [
      "Augmentation",
      2
    ],
    "type": 4
  },
  "beards": {
    "code": [
      "Beards",
      2
    ],
    "type": 4
  },
  "beastQuest": {
    "code": [
      "BeastQuest",
      2
    ],
    "type": 4
  },
  "bestiary": {
    "code": [
      "Bestiary",
      2
    ],
    "type": 4
  },
  "bloodMagic": {
    "code": [
      "BloodMagic",
      2
    ],
    "type": 4
  },
  "boostState": {
    "code": [
      "UnityEngine.Random+State",
      3
    ],
    "type": 4
  },
  "bossAttack": {
    "code": 6,
    "type": 0
  },
  "bossCurHP": {
    "code": 6,
    "type": 0
  },
  "bossDefense": {
    "code": 6,
    "type": 0
  },
  "bossID": {
    "code": 8,
    "type": 0
  },
  "bossMaxHP": {
    "code": 6,
    "type": 0
  },
  "bossMulti": {
    "code": 6,
    "type": 0
  },
  "bossRegen": {
    "code": 6,
    "type": 0
  },
  "capEnergy": {
    "code": 9,
    "type": 0
  },
  "cards": {
    "code": [
      "Cards",
      2
    ],
    "type": 4
  },
  "challenges": {
    "code": [
      "Challenges",
      2
    ],
    "type": 4
  },
  "cooking": {
    "code": [
      "Cooking",
      2
    ],
    "type": 4,
    "value": "texol"
  },
  "curEnergy": {
    "code": 9,
    "type": 0
  },
  "curHP": {
    "code": 6,
    "type": 0
  },
  "currentHighestBoss": {
    "code": 8,
    "type": 0
  },
  "daily": {
    "code": [
      "DailyReward",
      2
    ],
    "type": 4
  },
  "defense": {
    "code": 6,
    "type": 0
  },
  "defenseBoost": {
    "code": 11,
    "type": 0
  },
  "defenseMulti": {
    "code": 6,
    "type": 0
  },
  "diggers": {
    "code": [
      "GoldDiggers",
      2
    ],
    "type": 4
  },
  "energyBarProgress": {
    "code": 11,
    "type": 0
  },
  "energyBars": {
    "code": 9,
    "type": 0
  },
  "energyGained": {
    "code": 9,
    "type": 0
  },
  "energyPerBar": {
    "code": 8,
    "type": 0
  },
  "energyPower": {
    "code": 11,
    "type": 0
  },
  "energySpeed": {
    "code": 11,
    "type": 0
  },
  "exp": {
    "code": 8,
    "type": 0
  },
  "firstBossEver": {
    "code": 1,
    "type": 0
  },
  "firstTimePlaying": {
    "code": 1,
    "type": 0
  },
  "gold": {
    "code": 11,
    "type": 0
  },
  "hacks": {
    "code": [
      "Hacks",
      2
    ],
    "type": 4
  },
  "highestBoss": {
    "code": 8,
    "type": 0
  },
  "highestHardBoss": {
    "code": 8,
    "type": 0
  },
  "highestSadisticBoss": {
    "code": 8,
    "type": 0
  },
  "hpRegen": {
    "code": 6,
    "type": 0
  },
  "idleEnergy": {
    "code": 9,
    "type": 0
  },
  "inventory": {
    "code": [
      "Inventory",
      2
    ],
    "type": 4
  },
  "lastTime": {
    "code": 8,
    "type": 0
  },
  "lootBoxes": {
    "code": [
      "LootBoxes",
      2
    ],
    "type": 4
  },
  "lootState": {
    "code": [
      "UnityEngine.Random+State",
      3
    ],
    "type": 4
  },
  "machine": {
    "code": [
      "TimeMachine",
      2
    ],
    "type": 4
  },
  "magic": {
    "code": [
      "Magic",
      2
    ],
    "type": 4
  },
  "maxHP": {
    "code": 6,
    "type": 0
  },
  "nextAttackMulti": {
    "code": 6,
    "type": 0
  },
  "nextDefenseMulti": {
    "code": 6,
    "type": 0
  },
  "nextRebirthDifficulty": {
    "code": [
      "difficulty",
      2
    ],
    "type": 4
  },
  "oldBossMulti": {
    "code": 6,
    "type": 0
  },
  "oldTimeMulti": {
    "code": 6,
    "type": 0
  },
  "perks": {
    "code": [
      "Perks",
      2
    ],
    "type": 4
  },
  "pit": {
    "code": [
      "Pit",
      2
    ],
    "type": 4
  },
  "playerName": {
    "code": null,
    "type": 1
  },
  "portraits": {
    "code": [
      "PlayerPortraits",
      2
    ],
    "type": 4
  },
  "purchases": {
    "code": [
      "Purchases",
      2
    ],
    "type": 4
  },
  "realExp": {
    "code": 9,
    "type": 0
  },
  "realGold": {
    "code": 6,
    "type": 0
  },
  "rebirthTime": {
    "code": [
      "PlayerTime",
      2
    ],
    "type": 4
  },
  "res3": {
    "code": [
      "Resource3",
      2
    ],
    "type": 4
  },
  "settings": {
    "code": [
      "PlayerSettings",
      2
    ],
    "type": 4
  },
  "stats": {
    "code": [
      "Stats",
      2
    ],
    "type": 4
  },
  "timeMulti": {
    "code": 6,
    "type": 0
  },
  "totalPlaytime": {
    "code": [
      "PlayerTime",
      2
    ],
    "type": 4
  },
  "training": {
    "code": [
      "Training",
      2
    ],
    "type": 4
  },
  "version": {
    "code": 8,
    "type": 0
  },
  "wandoos98": {
    "code": [
      "Wandoos98",
      2
    ],
    "type": 4
  },
  "wishes": {
    "code": [
      "Wishes",
      2
    ],
    "type": 4
  },
  "yggdrasil": {
    "code": [
      "Yggdrasil",
      2
    ],
    "type": 4
  }
}
```
[NGUSave-Build-1260-avril-03-15-20.txt](https://github.com/AxesOfEvil/NGU-save-parser/files/8421444/NGUSave-Build-1260-avril-03-15-20.txt). It comes from a build 1260 on Windows from Steam from 2 days ago.

The save file I'm using is there

**Comment by tex0l** [comment]
I think there's an error in this parsing as the string `"texol"` that appears in the cooking has nothing to do there, texol being my username

**Comment by PhracturedBlue** [comment]
that may be related to the 'fix' for elem==6.  you could throw a breakpoint in there, and try to debug, otherwise, I'll need to do an upgrade and dig in.

**Comment by tex0l** [comment]
Damn it.. When uncommenting the debug logs, I messed with the indentation of the for loop of `get_class_values` :/ This whole thing with the type 6 where there shouldn't be one is my fault.

The type 14 thing you gave fixes the issue

I'll make a PR with something that works

Sorry about that, and thanks for the help.

**Comment by AxesOfEvil** [comment]
Thanks for doing the cleanup
